### ISSUE TITLE
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by kartikdanidhariya** [dilawar/pymoodle#1]
hi,
i try your script but it not logging in moodle 
it return following error

Initializing moodle ... 
Reading configuration file ...
Ignoring proxy variables...
Logging into Moodle ..
Traceback (most recent call last):
  File "moodle.py", line 434, in <module>
    moodle.make_connection()
  File "moodle.py", line 337, in make_connection
    res = self.br.open(self.url)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

please help ,
Thanks in advance!!!

**Comment by dilawar** [comment]
Could you post your moodlerc file?

**Comment by kartikdanidhariya** [comment]
hi,
after correction in url it work 
but i want to just autologin in moodle 
after run this script when i open "http://site.com/moodle/my/" so it redirect on http://site.com/moodle/login/index.php 

i try to open in script
webbrowser.open('http://site.com/moodle/my/')
but it redirect in index.php page

but i just want to open automatically
http://site.com/moodle/my/
as login user in browser
so how can i get that

**Comment by dilawar** [comment]
Well, this can be done but it would change the behavior of standard moodle login. So in this repo, I won't fix it.

If you want a script which works in your specific case, you can fork the repo and I'd suggest the appropriate changes.  Or better, if you could create a  test account on your site, I can make test the script as well.
